### ISSUE TITLE
support for python3

### ISSUE THREAD

**Issue by psifertex** [murx-/devi_binja#1]
This plugin currently does not list plugin3 compatibility in the plugin.json. If it is compatible with python3, please update the plugin.json and submit a new release for the plugin manager.

If the plugin isn't actually compatible yet, please consider adding python3 support. 

Binary Ninja will be requiring all plugins to be compatible with python3 and will remove plugins that only support python2 from the plugin manager at some point.

Thanks!

**Comment by murx-** [comment]
thanks for raising the issue and thanks for Binary Ninja! I specified python 3 support and open an issue in the community-plugins repo.

**Comment by psifertex** [comment]
You're welcome! :-) 

Thanks for the update, should be live now. One other small suggestion for the next update -- if you put the contents of the README.md inside of the `longdescription` in the plugin.json, you'll get much prettier plugin status pages. Note though that you want to be careful how you include images. Snippets is a [decent example](https://github.com/Vector35/snippets/blob/master/plugin.json).

Current look:

<img width="1113" alt="Screen Shot 2020-11-04 at 11 33 22 AM" src="https://user-images.githubusercontent.com/140215/98138873-8d05f080-1e91-11eb-9452-fb0ded829f0d.png">
